name: learning_assistant
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Make sure your Flutter/Dart SDK version matches or is compatible
  sdk: '>=3.0.0 <4.0.0' # Adjusted for better compatibility range

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # You have this, can be useful for other fonts
  webview_flutter: ^4.4.2 # Use latest compatible versions
  webview_flutter_android: ^4.3.2 # Use latest compatible versions
  webview_flutter_wkwebview: ^3.14.0 # Use latest compatible versions

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    # - assets/all_mcqs_combined.json
    # - data.json 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # --- Assets Section ---
  # To add assets to your application, add an assets section, like this:
  # This line declares the general assets folder.
  # Ensure you have an 'assets' folder in your project root
  # and place data.json, images, etc., inside it.
  

  # --- Fonts Section ---
  # To add custom fonts to your application, add a fonts section here.
  fonts:
    - family: OpenDyslexic  # This is the name used in your Theme code
      fonts:
        # Ensure the path 'assets/fonts/OpenDyslexic-Regular.otf' is correct.
        # Create an 'assets' folder, then a 'fonts' subfolder inside it,
        # and place your OpenDyslexic font file there.
        # Rename the file/path below if yours is different (e.g., .ttf extension).
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        # If you have other styles (bold, italic), add them like this:
        # - asset: assets/fonts/OpenDyslexic-Bold.otf
        #   weight: 700
        # - asset: assets/fonts/OpenDyslexic-Italic.otf
        #   style: italic

# ... rest of pubspec.yaml might follow ...